application: get-etymology
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.app
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"